name = "CameraModels"
uuid = "32837083-90d6-4313-9d41-6345427b552c"
authors = ["yakir12 <12.yakir@gmail.com>"]
version = "0.1.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
